// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDEIFnteYuHVTUbj_SqSu9lSnKJADoxX0Y',
    appId: '1:993553191553:web:d6a9d65dc5d4115bf6f380',
    messagingSenderId: '993553191553',
    projectId: 'registercommerce-191a2',
    authDomain: 'registercommerce-191a2.firebaseapp.com',
    storageBucket: 'registercommerce-191a2.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBTQq3Sci29qAWBtkujftmVkp5ri0IOvMs',
    appId: '1:993553191553:android:4f334abd297d5ff3f6f380',
    messagingSenderId: '993553191553',
    projectId: 'registercommerce-191a2',
    storageBucket: 'registercommerce-191a2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAIasL4bb5sqBu19hVwL5DeUoxPAJBR_4E',
    appId: '1:993553191553:ios:38403001e43c23c3f6f380',
    messagingSenderId: '993553191553',
    projectId: 'registercommerce-191a2',
    storageBucket: 'registercommerce-191a2.appspot.com',
    iosBundleId: 'com.example.finalProjectAdmin',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAIasL4bb5sqBu19hVwL5DeUoxPAJBR_4E',
    appId: '1:993553191553:ios:52bbac9bd72925dff6f380',
    messagingSenderId: '993553191553',
    projectId: 'registercommerce-191a2',
    storageBucket: 'registercommerce-191a2.appspot.com',
    iosBundleId: 'com.example.finalProjectAdmin.RunnerTests',
  );
}
